name: Build and Push ERP Image V16

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REPO_PATH: https://github.com/frappe/frappe
      GIT_BRANCH: version-16
      PYTHON_VERSION: "3.14.3"
      NODE_VERSION: "24.14.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Encode apps.json to base64
        id: apps
        run: |
          APPS_JSON_BASE64=$(cat apps.json | jq -c . | base64 -w0)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push ERP Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile   # change if custom path
          push: true
          build-args: |
            GIT_REPO_PATH=${{ env.GIT_REPO_PATH }}
            GIT_BRANCH=${{ env.GIT_BRANCH }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
            GH_PAT=${{ secrets.GH_PAT2 }}
          tags: |
            cogniquaint/test16:${{ steps.vars.outputs.VERSION }}
            cogniquaint/test16:latest